### ISSUE TITLE
Protect custom WP posts

### ISSUE THREAD

**Issue by danielwestendorf** [memberful/memberful-wp#126]

**Comment by danielwestendorf** [comment]
- [ ] Notify [Alvaro de la Maza](https://app.intercom.io/a/apps/23ea8a68117cf2cf2d2598a7b59c5d76425ee46b/inbox/conversation/720227805)

**Comment by dstrojny** [comment]
I think this is stretching the scope of the plugin. This could be handled with a custom function by a WP developer. Closing.
