### ISSUE TITLE
Private User RSS Feeds

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#131]
## Overview

WordPress Users with specified Memberful Subscription Plan(s) will get a **full user specific RSS feed (all posts)** with the default WordPress RSS formatting. This should be a **completely custom RSS feed**, as the plugin already hides parts of protected posts from the default RSS feed. We also want to avoid collisions with a WordPress theme that may be modifying the default RSS feed to exclude certain posts.

## Scope

1. Functionality to be included in the [Memberful WP plugin](https://github.com/memberful/memberful-wp) under a new tab on the existing Settings page labeled **RSS Feed**.
2. From the RSS Feed tab on the Settings page, the admin chooses specific Memberful Subscription Plans required for access (re-use the plan selector found elsewhere in the plugin).
3. If the WordPress user has the specified access[[1]]( https://memberful.com/help/integrate/services/wordpress/wordpress-functions/) as detailed in the previous step, generate a custom RSS feed for that user[[2]](http://wordpress.stackexchange.com/questions/46074/allow-users-to-create-their-own-feed-from-selected-categories) that has been hashed[[3]](https://github.com/adamfranco/private-feed-keys/blob/master/private-feed-keys.php) (so it isn’t guessable).
4. Provide a function for outputting the private user RSS Feed URL in a WordPress template and provide a shortcode for outputting it in a post or page. If the user doesn’t have access the function and the shortcode should instead display “You don’t have access to this RSS feed.” Display the function code and the shortcode in a note in the RSS Feed tab for convenience (I will style this).

## Important condition!

When the `is_subscribed_to_memberful_plan( $slug )` condition changes to false for that user (which will happen periodically), **the RSS feed should no longer work**. If it changes back to true, **the RSS feed should work again**. It’s not good enough just to hide the unique Feed URL if the condition is false, the feed **must also stop working** as the user will have already added the URL to their RSS reader.

**Comment by monkbent** [comment]
Looks good

**Comment by greguly** [comment]
Sounds doable.

**Comment by dstrojny** [comment]
@rusuandreirobert Here's a list of items I've come up with while testing...

**General**

- [ ] The the first checkbox is still not unchecking for me when I **Save Changes**. Any idea why?
- [ ] Ensure we're following the [WordPress PHP coding conventions](https://make.wordpress.org/core/handbook/coding-standards/php/). One that I know we're missing in some of the files is **tabs instead of spaces**.

**Feed**

- [ ] Ensure the feed format matches the default WordPress feed exactly. Right now there are some minor discrepancies and errors: language is missing and HTML isn't being output. To see the differences, diff the source of the default WordPress feed (`/?feed`) against the private feed (`?memberful-feed=XYZ`).
- [ ] Add some different types of content (links, images, video, etc.) and make sure the RSS feed source still matches the WordPress default feed format.
- [ ] Validate the feed at the [W3C Feed Validator](http://validator.w3.org/feed/#validate_by_input).
- [ ] Make the feed hash a bit longer (30 characters).

**Shortcode**

- [ ] Output the shortcode link as an actual link &rarr; [http://wordpress.dev/?memberful-feed=4848553035586591b](http://wordpress.dev/?memberful-feed=4848553035586591b).
- [ ] Make sure the shortcode gets a new paragraph when returned below text. Maybe this is a general shortcode problem (see screenshots)? 
- [ ] If possible, add the shortcode to the shortcode UI (see screenshot) **only when a Plan is selected** . The title for the item should be **Private RSS feed link**.

![screen shot 2015-04-17 at 10 29 41 am](https://cloud.githubusercontent.com/assets/427900/7203976/c4c55d2e-e4ec-11e4-8ec1-67e15c2df115.png)
![screen shot 2015-04-17 at 10 29 18 am](https://cloud.githubusercontent.com/assets/427900/7203988/dc3b923e-e4ec-11e4-964a-ceb0ef310b75.png)
![screen shot 2015-04-17 at 10 31 41 am](https://cloud.githubusercontent.com/assets/427900/7204008/09199526-e4ed-11e4-90c1-b00424a64b40.png)

**Comment by rusuandreirobert** [comment]
Handling everything now, seems like you've overrided one of my changes, no problem, I'll handle it.

**Comment by dstrojny** [comment]
Done! Closing.
