### ISSUE TITLE
SSL Warnings

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#136]
We need to make it clear that SSL should be used with the plugin to avoid browser security warnings. To do this, we should:

Display a (dismissable?) global warning notice in the WordPress admin when you are connected to Memberful with the plugin and **either** of the following conditions are met:

1. You have a Site URL or Home URL that **does not use** `https://`
2. You are not [forcing SSL for WP admin logins](https://codex.wordpress.org/Administration_Over_SSL).

**The notice messages**

1. Please install an SSL certificate and [set your Site URL and Home URL](/wp-admin/options-general.php) to start with `https://` or your members may receive browser security warnings.
2. Please [force SSL logins](https://codex.wordpress.org/Administration_Over_SSL) by adding `define('FORCE_SSL_ADMIN', true);` to your `wp-config.php` file or your members may receive browser security warnings.

**Comment by dstrojny** [comment]
Just thought of something @rusuandreirobert. Can we require that you're connected to Memberful before showing this warning? Similar to the check we ran on the cron job. There is no point in warning people before they've even connected the plugin.

**Comment by rusuandreirobert** [comment]
Can you check also ? :) on the phone and I tried on my site first
