### ISSUE TITLE
Better syncing of Site / Home URLs

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#137]
Right now, you need to disconnect and reconnect the plugin from Memberful to reset the WordPress **Site URL** and **Home URL** for Memberful. Ideally:

* Clicking the **Manual Sync** button would sync this information.
* When the Site URL or Home URL **changes**, the plugin syncs the new values to Memberful.

Let me know if the second option is difficult or problematic.

**Comment by dstrojny** [comment]
@rusuandreirobert What was the limitation here? Not possible with the current API we're providing from Memberful?

**Comment by rusuandreirobert** [comment]
I've spent 1 hour checking the code and I have no idea how to do this :P. I can't invest more time looking into it honestly, taking into consideration all the details we've talked privately.

**Comment by dstrojny** [comment]
Fair enough, thanks for letting me know!

**Comment by dstrojny** [comment]
I think it makes sense to force a disconnect / reconnect for this action. Closing.
