### ISSUE TITLE
Only run syncing functions if site is connected to Memberful

### ISSUE THREAD

**Issue by coreymckrill** [memberful/memberful-wp#138]
### Please be careful with this. We don't want to somehow degrade or break the syncing.

Right now, the cron functions run regardless of whether the site is actively connected:
https://github.com/memberful/memberful-wp/blob/develop/src/cron.php#L3-L13

In most cases, this is fine since the sync will fail if the plugin settings haven't been configured yet. However, adding a check to see if the site has an active Memberful connection before adding the cron events prevents unnecessary remote connection attempts.

**Comment by rusuandreirobert** [comment]
Hey,

Do you want to not register the cron events until it's configured, or simply add a verification ( if statement ) on each run ? I think the second option is safer to go, as it wouldn't need as much testing.

**Comment by dstrojny** [comment]
> Do you want to not register the cron events until it's configured, or simply add a verification ( if statement ) on each run ? I think the second option is safer to go, as it wouldn't need as much testing.

I would agree that the if statement seems much more prudent in this case. We should also check to make sure the "active Memberful connection" check is 100% accurate. We don't want sites failing to run the cron job because they "think" they're not connected, but they are.

Any thoughts @coreymckrill?

**Comment by coreymckrill** [comment]
> We don't want sites failing to run the cron job because they "think" they're not connected, but they are.

Agreed. It's not clear to me how this would be tested. There are several plugin settings, but I'm not sure if any of them specifically indicate that the site is connected.

**Comment by rusuandreirobert** [comment]
```php
if( get_option( 'memberful_api_key' , '') != '' )
```

That's the best thing I've found and tested, because without that the API request can't even happen.

As seen on the "primary" sync function.

```php
function memberful_wp_fetch_entities( $url ) {
	$full_url = add_query_arg( 'auth_token', get_option( 'memberful_api_key' ), $url );

	$response = wp_remote_get( $full_url, array( 'sslverify' => MEMBERFUL_SSL_VERIFY ) );
        // ........
}
```

**Comment by coreymckrill** [comment]
Works for me.
