### ISSUE TITLE
Prevent plugin settings from syncing to Memberful on development environments

### ISSUE THREAD

**Issue by coreymckrill** [memberful/memberful-wp#139]
At least twice now, we've had a local development version of the TTF site sync its Memberful settings back to the Memberful production server, updating the site's URL to our development domain, `thethemefoundry.dev`. The only way to (hopefully) prevent this seems to be manually blanking out the value of the `memberful_site` option, which will cause remote requests to the Memberful endpoint to fail.

It would be great if there was a better, more permanent way to prevent this. Perhaps the plugin could look for a `MEMBERFUL_SITE_URL` constant before using the value in the database. Or even just checking for the presence of a `MEMBERFUL_DEV` constant before syncing data.

**Comment by dstrojny** [comment]
We addressed this partly in #138. As long as the API key value is empty, the plugin will not run any automatic syncing. Therefore, for development environments, just clear out the Memberful API key value and you should be all set. I'm going to close this for now.
