### ISSUE TITLE
Add changelog entry for 1.17.1, update "Tested up to" version to 4.2.1 

### ISSUE THREAD

**Issue by coreymckrill** [memberful/memberful-wp#141]

**Comment by dstrojny** [comment]
Can we throw this into the mix at the end @rusuandreirobert? Should be a single line change.

**Comment by rusuandreirobert** [comment]
Smallest detail :) We'll handle it at the end.

**Comment by dstrojny** [comment]
As testing is about wrapped up, can we add this now @rusuandreirobert? We're now at 4.2.2.

**Comment by rusuandreirobert** [comment]
In the readme.txt, right ?
