### ISSUE TITLE
bbPress: Send them to a specific URL won't save

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#147]
- [ ] Notify Brandon

When using the bbPress integration, the "Send them to a specific URL" setting won't save when you set it. Example below.

![nosave](https://cloud.githubusercontent.com/assets/427900/7823569/602a2d34-03ca-11e5-827c-02e6514e6d06.gif)

**Comment by rusuandreirobert** [comment]
Does the URL change on save ? Or not ? I want to determine if the right checkbox isn't "opened" or if the save isn't happening

**Comment by dstrojny** [comment]
No the URL doesn't change on Save.

**Comment by dstrojny** [comment]
Hey @rusuandreirobert, I'm still seeing this problem on my live test site with these changes.

**Comment by rusuandreirobert** [comment]
@dstrojny please send me temporary access via email, and I'll have a look tonight, i think it's a conflict with something, not sure why

**Comment by dstrojny** [comment]
@rusuandreirobert Sent! Let me know if you did not receive the email.

**Comment by rusuandreirobert** [comment]
@dstrojny Seems like I didn't receive it
