### ISSUE TITLE
PHP notice on Bulk restrict access tool page

### ISSUE THREAD

**Issue by sumobi** [memberful/memberful-wp#150]
While viewing the `Bulk restrict access tool` tab in the settings, there's a PHP notice shown:

    PHP Notice:  Undefined variable: viewable_by_any_registered_users in /wp-content/plugins/memberful-wp/views/acl_selection.php on line 3

**Comment by tnorthcutt** [comment]
Looks like [this is fixed now](https://github.com/memberful/memberful-wp/blob/c2fe777a1da95058479d9aa534cb536d934d1104/readme.txt#L54).
