### ISSUE TITLE
Make option tabs extendable

### ISSUE THREAD

**Issue by tnorthcutt** [memberful/memberful-wp#155]
Right now, the various option tab views, eg. [`views/bulk_protect.php`](https://github.com/memberful/memberful-wp/blob/e159a611e6c730a14a3b2e14655a0b967a510d12/views/bulk_protect.php) are pretty much hardcoded. Would you be open to making those extendable, so that other plugins could hook in and add settings to those tabs?

My use case: I have a site where we need to have post-specific marketing content, but also a piece of content that goes after the post-specific marketing content which will be the same across all posts – basically a CTA to join the site. I could of course create a setting for that somewhere else, but sine it would be logically related to the Memberful functionality, it seems to make sense to put it on the Memberful options page.

I'm happy to submit a PR to add this if you'd like – just let me know any preferred implementation methods :+1:

**Comment by dstrojny** [comment]
Great idea @tnorthcutt! A PR would be fantastic. We don't have any specific implementation methods, as we're obviously a bit lacking in this area. If you could, just keep it consistent and in line with WordPress best practices.
