### ISSUE TITLE
More debug information for OAuth fail

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#158]
We need to send debug information for [OAuth webhook failures](https://github.com/memberful/memberful-wp/blob/master/src/authenticator.php#L171-L176) to the [debug error log](https://github.com/memberful/memberful-wp/blob/baed939b5dbf8f16afa4510a7f726f99d23b18be/src/admin.php#L171-L211) so we can better diagnose problems.

This has already been attempted in the [158-oauth-debug branch](https://github.com/memberful/memberful-wp/tree/158-oauth-debug). It is **not complete** and **needs to be tested** and possibly refactored before we actually release it on live sites.

**Comment by dstrojny** [comment]
For the record — moving the first attempt into it's own branch and hard resetting develop to fe3d512.

**Comment by rusuandreirobert** [comment]
@coreymckrill Do you strictly want to store this in the DB or you want to also do a hook request to your server ? From what I can see it successfully stores it in the DB, I did a "hackish" attempt to test. If you also want it to record it on your server, can you give me a few details ?

**Comment by dstrojny** [comment]
@rusuandreirobert We really just want to output it to the debug log that can be found at `wp-admin/options-general.php?page=memberful_options&subpage=debug`. I'm guessing the WordPress DB is sufficient for that purpose.
