### ISSUE TITLE
Sensei Support 

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#163]
We've had reports that the content protection doesn't work with the [Sensei plugin](http://www.woothemes.com/products/sensei/). This is probably because it uses a custom post type. I'm not sure about the feasibility of supporting it comprehensively, but maybe we could at least get the [WordPress shortcodes](https://memberful.com/help/integrate/services/wordpress/wordpress-shortcodes/) working with Sensei / Custom Post Types?

**Comment by rusuandreirobert** [comment]
i've checked and this works as intended, people with custom integrations that don't respect the hooks may have problems tough, also the rule to hude courses doesn't apply for admins and people who started the course ( neither the content filter )
