### ISSUE TITLE
Don't automatically sync site URLs

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#168]
We should consider not automatically syncing the site URLs. We've had a few people with staging sites get their main Memberful account accidentally connected to their staging site. If we remove it, the site admin would need to reconnect the plugin if the URL changes.

**Comment by mrhead** [comment]
@dstrojny this is done in #182. But I am not sure if it is going to help. Maybe yes, but not in all cases.

Do you know how the issues with staging sites happened? Did they just copy production database to staging and then we synchronized staging with Memberful from a cron job?

I've removed the cron job, but we still run this synchronization on site name or URL change. So if they just copy production DB to staging and then update site name or URL, then we synchronize it with Memberful again.
