### ISSUE TITLE
"Any registered user" checkbox not working

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#170]
Looks like we introduced a bug somewhere after version 1.18.1. A customer submitted a [screencast showing the problem](https://www.dropbox.com/s/kzazqcq94pvfwez/memberful-save.mov?dl=0). It looks like we previously had a similar issue in #128.

**Comment by mrhead** [comment]
I cannot move this ticket to the "In progress" column in Waffle. If I do it then it is moved to the backlog instead of "In progress".

**Comment by mrhead** [comment]
The bug was introduced in 1.19.0. Now I am going to check it out and hopefully find a solution for it.

**Comment by mrhead** [comment]
The issue was introduced here: https://github.com/memberful/memberful-wp/commit/4152e16f094c5c8d3df4e7d6c1584452833848c5.

**Comment by dstrojny** [comment]
> I cannot move this ticket to the "In progress" column in Waffle. If I do it then it is moved to the backlog instead of "In progress".

I think this has to do with the Label name here in Github matching Waffle. I've updated it, so it should work now in the future (hopefully).
