### ISSUE TITLE
This plugin does not have a valid header

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#174]
![install-error](https://cloud.githubusercontent.com/assets/427900/12066123/1d380374-afb0-11e5-9435-8c1da6f1588d.gif)

**Comment by mrhead** [comment]
I've identified the issue. It is caused by existence of [trunk/](http://plugins.svn.wordpress.org/memberful-wp/tags/1.21.1/trunk/) directory in the repository. It was accidentally added and it shouldn't be there.

**Comment by mrhead** [comment]
Fixed! http://plugins.svn.wordpress.org/memberful-wp/tags/1.21.1/trunk/ doesn't exist anymore.

Happy new year everyone! :tada:

**Comment by dstrojny** [comment]
Nice! Thanks Patrik! :+1:
