### ISSUE TITLE
Fix debug page

### ISSUE THREAD

**Issue by mrhead** [memberful/memberful-wp#175]
We had a customer with blank Memberful WP debug page. This was caused by this code:

```php
<?php if ( $total_unmapped_users > 0 ): ?>
Unmapped users:
<?php echo str_pad('WP ID', 6), ' ', str_pad('Email', 30), ' ', 'Date registered' ?>
<?php foreach($unmapped_users as $unmapped_user): ?>

<?php echo str_pad($unmapped_user->ID, 6) ?> <?php echo str_pad($unmapped_user->user_email, 30) ?> <?php echo $unmapped_user->user_registered; ?>
<?php endforeach; ?>

<? endif; ?>
```

Todos:
- [ ] find a way how to reproduce this failure locally
- [ ] fix it

**Comment by mrhead** [comment]
@dstrojny This is a little bit off topic, but we should consider adding a debug link somewhere to admin pages. What do you think?

**Comment by dstrojny** [comment]
We definitely could add the link. I just don't see a convenient / clean place to insert it right now. In the past, I've generally just directed the customer to the URL directly.

**Comment by mrhead** [comment]
I am closing this. I can't reproduce it locally. Also this code is pretty straightforward and most probably we just hit some edge case before.
