### ISSUE TITLE
Use Memberful's Remember Me Setting

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#176]
On the Memberful side, we keep members signed in for 1 year, but on the WordPress side, the "Remember me" setting only lasts for 14 days. This results in members having to sign in pretty frequently, which can be a bad experience.

We should [override this via a filter]( http://wordpress.stackexchange.com/questions/515/whats-the-easiest-way-to-stop-wp-from-ever-logging-me-out) to match Memberful and make it a setting that is on by default.

One thing we should consider here — I've already told a few people to manually implement this filter in their theme, so we should avoid any namespace or other conflicts from the plugin adding it.

<img width="827" alt="screen shot 2016-01-20 at 2 42 30 pm" src="https://cloud.githubusercontent.com/assets/427900/12460895/14a61cd0-bf84-11e5-965e-6ff3118ff64b.png">

**Comment by dstrojny** [comment]
One thing we should consider here — I've already told a few people to manually implement this filter in their theme, so we should avoid any namespace or other conflicts from the plugin adding it.

**Comment by dstrojny** [comment]
Added a screenshot of the UI.

**Comment by mrhead** [comment]
Do we have anyone who could do this for us? My PHP and WordPress knowledge is limited. I could probably do it, but it would take me a lot of time. Especially when we need to be sure that we are not going to break anything...

**Comment by dstrojny** [comment]
Yes, definitely. I can ask @rusuandreirobert about it.
