### ISSUE TITLE
Run user creation in DB transaction

### ISSUE THREAD

**Issue by mrhead** [memberful/memberful-wp#207]
I am not sure if this is possible, but it could help us avoid issues like we had in #206. Where a WordPress user has been created, but then the request failed before we created an entry in `wp_memberful_mapping` so we couldn't map WordPress users to Memberful members.

**Comment by dstrojny** [comment]
Isn't this the same idea in #153? From that issue:

>  Ideally, we'd wrap the whole WordPress user creation and Memberful mapping process in a transaction, but as WordPress doesn't require InnoDB, we can't rely on it being present.

**Comment by mrhead** [comment]
Yes, it is the same idea! I'm closing this issue in favour of #153. But we should definitely address it.
