### ISSUE TITLE
Allow WP roles to be matched up with products or subscriptions.

### ISSUE THREAD

**Issue by dstrojny** [memberful/memberful-wp#27]
## Rough Spec
- Add two role mappings `role for active subscriber`, `role for inactive subscriber`
- Purchasing a download will not give the customer the `active subscription` role. => If they have a download and no sub then they receive the `inactive subscriber role`. **DISCUSSION:** Should they receive the `active subscriber` role? Can only apply one role at a time.
- When the customer's last active subscription expires we change their role from `active subscriber`, to the `inactive subscriber`.
- We'll change the user's role when we sync their account at sign in, by webhook, or by cron
- As plugins may use a user's role when the user themself is not signed in (e.g. admin panel, bbPress), it's imperative that we keep the sync uptodate if webhooks happen to fail. This feature therefore relies on the cronjob #75 
- The roles will be configurable via a panel in the Memberful settings page
- If a user has a role other than `subscriber` (WordPress' role), `active subscriber` or `inactive subscriber` then we DO NOT change their role at any time. This should prevent admins and writers from being demoted. 
- Based on previous point, only the `subscriber` role and non-WordPress default roles will be available in the dropdowns as it would open the potential for admins to be demoted by the plugin, which is something we want to avoid.
## Edits 2014-05-12:
- Only consider members who have a mapping from Memberful

**Comment by damienroue** [comment]
Hi there. Not sure if that's the right place for that.
I installed Memberful on a WP blog and created two custom roles for active and inactive subscribers. Unfortunately, when someone sign up on Memberful for our site, the user is not given any particular role in Wordpress (role is none) and it doesn't go to the roles set up for active and inactive subscribers.

The thing is: I am in test mode, not yet in production. Could this be the reason?
