### ISSUE TITLE
Prevent password reset on assigned custom role rather than subscriber

### ISSUE THREAD

**Issue by jeremyfelt** [memberful/memberful-wp#279]
👋🏻 Thanks for the plugin!

We recently changed the role associated with Memberful generated users to a custom "Memberful Member" role so that standard registration could still be used for the Subscriber role. The assignment of the custom role is working great, but [the subscriber role is hard coded](https://github.com/memberful/memberful-wp/blob/fb2a661042ac0aebe91800ed44e40f4635bb4de9/wordpress/wp-content/plugins/memberful-wp/src/authenticator.php#L14-L24) into `Memberful_Authenticator::audit_password_reset()`, so the password reset prevention is no longer (I think) assigned to the correct role.

I've addressed this in code with the following:

```
// Prevent Memberful from preventing registration for subscribers.
remove_filter( 'allow_password_reset', array( 'Memberful_Authenticator', 'audit_password_reset' ), 50 );

// Reproduce that same Memberful functionality on a different role.
add_filter( 'allow_password_reset', __NAMESPACE__ . '\prevent_memberful_member_password_reset', 99, 2 );

....etc
```

I'm wondering if the `audit_password_reset` method could check Memberful settings and use the role set there instead.

**Comment by northerner** [comment]
Hi @jeremyfelt, thanks for raising this.

I'll need to dig in more on this first and get some testing done. But on the face of it this looks like a sensible change.

I'll aim to get back to you this week with the update.

**Comment by northerner** [comment]
Hey @jeremyfelt, as you can see above this change is on the way. Expecting it to be deployed this week.

https://github.com/memberful/memberful-wp/pull/282
